"""add password_hash to user

Revision ID: 810140659eeb
Revises: 
Create Date: 2023-04-16 18:45:30.710894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810140659eeb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=100), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
